version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8319:8319"

  frontend:
    image: node:22-alpine
    working_dir: /app
    # Montujemy kod i .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./.env:/app/.env
    ports:
      - "8320:8320"      # host:container
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
