services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8319:8319"

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      env_file:
        - ./frontend/.env
      environment:
        - REACT_APP_API_URL=http://backend:8319
      depends_on:
        - backend
      ports:
        - "8320:8320"