services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8319:8319"

  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=3000
    ports:
      - "8320:3000"
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
