services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8319:8319"

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app         # kod frontendu
      - /app/node_modules       # cache node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8319
    ports:
      - "3000:3000"
    command: npm install && npm start
    depends_on:
      - backend
