# Etap 1: budowa zależności Pythona
FROM python:3.12-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# Etap 2: finalny obraz\ nFROM python:3.12-slim
WORKDIR /app
ENV PATH=/root/.local/bin:$PATH

# Przenosimy z buildera
COPY --from=builder /root/.local /root/.local

# Kopiujemy kod i entrypoint
COPY . .
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Odpalenie migracji i aplikacji
ENTRYPOINT ["/entrypoint.sh"]
CMD ["gunicorn", "mediscan.wsgi:application", "--bind", "0.0.0.0:8319"]