# Etap 1: budowa zależności
FROM python:3.12-slim AS builder
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# Etap 2: finalny obraz
FROM python:3.12-slim
WORKDIR /app
ENV PATH=/root/.local/bin:$PATH
COPY --from=builder /root/.local /root/.local
COPY backend/ .
COPY --from=frontend-build /app/frontend/build/ ./static/
CMD ["gunicorn", "mediscan.wsgi:application", "--bind", "0.0.0.0:8319"]